### ISSUE TITLE
Updated design

### ISSUE THREAD

**Issue by iDuuck** [sketchpacks/sketchpacks.com#9]
Hey, I really like the idea of strive onto a page like npmjs for sketch plugins, so I did a quick draft in the direction of the npm homepage:

![desktop hd](https://cloud.githubusercontent.com/assets/325241/13839449/69c600ea-ec1b-11e5-96c7-5061854347f4.png)

What do you guys or especially @adamkirkwood thinks about this?

Edit: Most functionality is possible at the moment (except the command line interface).

**Comment by adamkirkwood** [comment]
@iDuuck This is great! This structure is exactly what I had in mind.

I work on a UI update and will push it to a staging server. I will be sure to ping you so you can also have a look at it.

Also, I love the idea of having a CLI. I know @almonk has his [CLI project](https://github.com/almonk/dpm), but I'm unsure of its progress. Are you familiar with writing CLIs?

I plan on making a simple first version of an API (#8) soon.

Thank you!

**Comment by iDuuck** [comment]
I am sure familiar with CLI projects.
What do you want to go with? Node.js, Ruby (because this project is also Rails), or Bash?

Be sure to keep me in the loop about the redesign!

**Comment by adamkirkwood** [comment]
@iDuuck Perhaps we can poll the Sketch Community and see what their preferred language for CLIs are. 

Since all plugins are written in JavaScript, I assume people would be more comfortable with a Node.js CLI.

If you're interested in developing this CLI, I'd be more than happy if you could. We can begin by thinking about what would be useful for plugin authors and Sketch users who might be using this CLI.

**Comment by iDuuck** [comment]
CLI sounds good. Please add a new repository and add me to the sketchpacks group so we can discuss further.
